CREATE TABLE [prodcopystg].[str_MarketingEventDetail]
(
[createdby] [uniqueidentifier] NULL,
[createdbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdon] [datetime] NULL,
[createdonbehalfby] [uniqueidentifier] NULL,
[createdonbehalfbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdonbehalfbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[exchangerate] [decimal] (28, 0) NULL,
[importsequencenumber] [int] NULL,
[modifiedby] [uniqueidentifier] NULL,
[modifiedbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedon] [datetime] NULL,
[modifiedonbehalfby] [uniqueidentifier] NULL,
[modifiedonbehalfbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedonbehalfbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[organizationid] [uniqueidentifier] NULL,
[organizationidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[overriddencreatedon] [datetime] NULL,
[statecode] [int] NULL,
[statecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[statuscode] [int] NULL,
[statuscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_attenddate] [datetime] NULL,
[str_clienttype] [int] NULL,
[str_clienttypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_comments] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_contactid] [uniqueidentifier] NULL,
[str_contactidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_contactidyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_estimatedattendees] [int] NULL,
[str_invitedate] [datetime] NULL,
[str_marketingeventdetailid] [uniqueidentifier] NOT NULL,
[str_marketingeventid] [uniqueidentifier] NULL,
[str_marketingeventidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_money1] [money] NULL,
[str_money1_base] [money] NULL,
[str_money2] [money] NULL,
[str_money2_base] [money] NULL,
[str_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_number1] [int] NULL,
[str_number2] [int] NULL,
[str_quantity] [int] NULL,
[str_response] [int] NULL,
[str_responsedate] [datetime] NULL,
[str_responsename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_text1] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_text10] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_text2] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_text3] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_text4] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_text5] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_text6] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_text7] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_text8] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_text9] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_totalattendees] [int] NULL,
[timezoneruleversionnumber] [int] NULL,
[transactioncurrencyid] [uniqueidentifier] NULL,
[transactioncurrencyidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[utcconversiontimezonecode] [int] NULL,
[versionnumber] [bigint] NULL,
[CopyLoadDate] [datetime] NOT NULL CONSTRAINT [const_stgMarketingEventDetail_CopyLoadDate] DEFAULT (getdate())
)
GO
ALTER TABLE [prodcopystg].[str_MarketingEventDetail] ADD CONSTRAINT [PK__str_Mark__58BC801291B4833E] PRIMARY KEY CLUSTERED  ([str_marketingeventdetailid])
GO
