CREATE TABLE [prodcopy].[str_MarketingEvent]
(
[createdby] [uniqueidentifier] NULL,
[createdbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdon] [datetime] NULL,
[createdonbehalfby] [uniqueidentifier] NULL,
[createdonbehalfbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdonbehalfbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[importsequencenumber] [int] NULL,
[modifiedby] [uniqueidentifier] NULL,
[modifiedbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedon] [datetime] NULL,
[modifiedonbehalfby] [uniqueidentifier] NULL,
[modifiedonbehalfbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedonbehalfbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[organizationid] [uniqueidentifier] NULL,
[organizationidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[overriddencreatedon] [datetime] NULL,
[statecode] [int] NULL,
[statecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[statuscode] [int] NULL,
[statuscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_category] [int] NULL,
[str_categoryname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_date] [datetime] NULL,
[str_description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_estimatedattendees] [int] NULL,
[str_marketingeventid] [uniqueidentifier] NOT NULL,
[str_money1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_money2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_number1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_number2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_text1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_text10] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_text2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_text3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_text4] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_text5] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_text6] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_text7] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_text8] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_text9] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_ticketsourceid] [uniqueidentifier] NULL,
[str_ticketsourceidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_totalaccepted] [int] NULL,
[str_totalattended] [int] NULL,
[str_totaldeclined] [int] NULL,
[str_totalinvited] [int] NULL,
[timezoneruleversionnumber] [int] NULL,
[utcconversiontimezonecode] [int] NULL,
[versionnumber] [bigint] NULL,
[CopyLoadDate] [datetime] NOT NULL CONSTRAINT [const_MarketingEvent_CopyLoadDate] DEFAULT (getdate())
)
GO
ALTER TABLE [prodcopy].[str_MarketingEvent] ADD CONSTRAINT [PK__str_Mark__FC9A430297F31654] PRIMARY KEY CLUSTERED  ([str_marketingeventid])
GO
